// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0vR8UonFbGxOA5Uxjikn9avyl2qPxJjo',
    appId: '1:388401607033:web:2bfb8f3a0ebf1c5d787fa8',
    messagingSenderId: '388401607033',
    projectId: 'kleanit-c4f88',
    authDomain: 'kleanit-c4f88.firebaseapp.com',
    storageBucket: 'kleanit-c4f88.firebasestorage.app',
    measurementId: 'G-DWJ6KHX6V7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp_cX1KLeV7ACn1EEJyTEuDXBAAFerAig',
    appId: '1:388401607033:android:797bec0fe3f7b28a787fa8',
    messagingSenderId: '388401607033',
    projectId: 'kleanit-c4f88',
    storageBucket: 'kleanit-c4f88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbulKlglQTjQvm0yRvtnzcC7_b4E3rX4A',
    appId: '1:388401607033:ios:a7b0cb840bc91b05787fa8',
    messagingSenderId: '388401607033',
    projectId: 'kleanit-c4f88',
    storageBucket: 'kleanit-c4f88.firebasestorage.app',
    androidClientId: '388401607033-1u0lfilr31rb1d4d1hmasdlstfja80gs.apps.googleusercontent.com',
    iosClientId: '388401607033-qalb40g4tdevu936c5ai8ij839gdpt9s.apps.googleusercontent.com',
    iosBundleId: 'com.kleanit.kleanitadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbulKlglQTjQvm0yRvtnzcC7_b4E3rX4A',
    appId: '1:388401607033:ios:a7b0cb840bc91b05787fa8',
    messagingSenderId: '388401607033',
    projectId: 'kleanit-c4f88',
    storageBucket: 'kleanit-c4f88.firebasestorage.app',
    androidClientId: '388401607033-1u0lfilr31rb1d4d1hmasdlstfja80gs.apps.googleusercontent.com',
    iosClientId: '388401607033-qalb40g4tdevu936c5ai8ij839gdpt9s.apps.googleusercontent.com',
    iosBundleId: 'com.kleanit.kleanitadmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0vR8UonFbGxOA5Uxjikn9avyl2qPxJjo',
    appId: '1:388401607033:web:dc57b5b6e9be84a5787fa8',
    messagingSenderId: '388401607033',
    projectId: 'kleanit-c4f88',
    authDomain: 'kleanit-c4f88.firebaseapp.com',
    storageBucket: 'kleanit-c4f88.firebasestorage.app',
    measurementId: 'G-BZTX6T86SV',
  );
}
